chore: :card_file_box: Alter table CUSTOMER_ORDER to add payment id
JessicaRodriguesdc/fiap-soat-tech-challenge pull request #10
Opened 2024-07-27 19:46 UTC by DiguyaDeveloper

## Created migrations to update order table

In this migration, we are adding a new column paymentId to the CUSTOMER_ORDER table. The paymentId column is of type VARCHAR(255) and is intended to store the identifier of the payment associated with the customer order.

Details:

Table: CUSTOMER_ORDER
New Column: paymentId
Data Type: VARCHAR(255)
This change will help in better tracking and management of payments related to customer orders within the system.

2024-07-28 15:24 UTC, 8bitbeard approved these changes

2024-07-29 00:29 UTC, JessicaRodriguesdc requested changes

2024-07-29 00:29 UTC, JessicaRodriguesdc commented on src/main/resources/db/migration/V5__update_order_table_add_payment_id.sql
> +ADD COLUMN PAYMENT_ID VARCHAR(255);
@DiguyaDeveloper Faz sentido criar um arquivo para editar ? visto que ainda não temos um banco "fisico", talvez daria para editar a propeia migração como você fez mudando o nome.

2024-07-29 02:10 UTC, DiguyaDeveloper commented on src/main/resources/db/migration/V5__update_order_table_add_payment_id.sql
> +ADD COLUMN PAYMENT_ID VARCHAR(255);
Faz sim! atualizei aqui

2024-07-29 22:17 UTC, alemiranda-dev approved these changes

2024-07-29 22:24 UTC, sartori00 approved these changes

2024-07-30 01:17 UTC, merged