feat: ✨ add swagger in new controllers and fix some things
JessicaRodriguesdc/fiap-soat-tech-challenge pull request #23
Opened 2024-08-03 16:19 UTC by sartori00

Guys, this PR was a little big, but necessary adjustments were made..

- UseCaseConfis was moved to config/bean
- FakeCheckout Swagger schemas were missing examples, I added them
- Created ApiResponses and Swagger Schemas for new Product Controllers
- Refactored the implementation of Pageable for Order because the way of implemented wasn't work good in Swagger
- Created ApiResponses and Swagger Schemas for Order Controllers
- Fixed cardinality of Customer x Order, because Customers may have more than one order, and OneToOne allows a customer to have only one order.
- Refactor to use Sequences from PostgreSQL to avoid competition and duplicate Sequences
- In UseCase findOrders, the isPaid parameter was HardCoded to 'false', I changed it to be dynamic receiving as a request parameter, but I think we should discuss the real need for this parameter. PREPARING Status only has unpaid orders, and orders with other statuses are paid 😕

That's it, have fun evaluating my PR 😄

2024-08-03 16:52 UTC, JessicaRodriguesdc approved these changes

2024-08-04 00:14 UTC, 8bitbeard approved these changes

2024-08-04 22:53 UTC, alemiranda-dev approved these changes

2024-08-05 02:21 UTC, DiguyaDeveloper requested changes

2024-08-05 20:58 UTC, sartori00 commented on src/main/java/br/com/fiap/tech_challenge/adapters/driver/api/openapi/OrderControllerOpenApi.java
> +    ResponseEntity<Page<OrderSummaryResponseDTO>> findAllIsPaidOrders(OrderStatus status, Boolean isPaid, int page, int size);
é cara, antes estava fixado como false, e só estava retornando pedidos não pago. mas de todo caso, no meio do caminho acabamos descobrindo que a partir do estado PREPARING todos os proximos já são pedidos pagos, e o status RECEIVED sempre vai retornar um pedido não pago, então me pergunto sobre a real necessidade deste campo. O status já representa muito bem o estado do pagamento.

2024-08-05 20:59 UTC, sartori00 commented on src/main/java/br/com/fiap/tech_challenge/config/openapi/schemas/PageableOrderResponseDTO.java
> +public record PageableOrderResponseDTO(
Acho que devemos avaliar a complexidade disso.

2024-08-05 20:59 UTC, sartori00 commented on src/main/java/br/com/fiap/tech_challenge/config/openapi/schemas/PageableProductResponseDTO.java
> +public record PageableProductResponseDTO(
Acho que devemos avaliar a complexidade disso.

2024-08-05 22:08 UTC, DiguyaDeveloper commented on src/main/java/br/com/fiap/tech_challenge/adapters/driver/api/openapi/OrderControllerOpenApi.java
> +    ResponseEntity<Page<OrderSummaryResponseDTO>> findAllIsPaidOrders(OrderStatus status, Boolean isPaid, int page, int size);
Também concordo sobre esse ponto dos STATUS

2024-08-05 22:08 UTC, DiguyaDeveloper commented on src/main/java/br/com/fiap/tech_challenge/config/openapi/schemas/PageableOrderResponseDTO.java
> +public record PageableOrderResponseDTO(
A complexidade é menor, pois acaba criando varias classes com as mesmas propriedades, sendo que os comportamentos sempre vão ser iguais.

Só onde encaixar essa classe comum que poderia dificultar um pouco, mas to resto é só extensibilidade

2024-08-05 22:08 UTC, DiguyaDeveloper commented on src/main/java/br/com/fiap/tech_challenge/config/openapi/schemas/PageableProductResponseDTO.java
> +public record PageableProductResponseDTO(
A complexidade é menor, pois acaba criando varias classes com as mesmas propriedades, sendo que os comportamentos sempre vão ser iguais.

Só onde encaixar essa classe comum que poderia dificultar um pouco, mas to resto é só extensibilidade

2024-08-05 22:08 UTC, DiguyaDeveloper approved these changes

2024-08-05 23:27 UTC, merged