feature: ✨Add test product
JessicaRodriguesdc/fiap-soat-tech-challenge pull request #24
Opened 2024-08-03 19:43 UTC by JessicaRodriguesdc

## Test units Product

- The OrderStatus enum class has been renamed to StatusOrderEnum.
- Unit tests for the Product, ProductEntity, CreateProductUseCaseImpl, UpdateProductUseCaseImpl, CreateProductUseCaseConfig, UpdateProductUseCaseConfig, ProductPersistenceImpl and ProductController classes have been added.
- Evidence of the feature:
build
![Captura de tela 2024-08-03 162645](https://github.com/user-attachments/assets/ea3dbf28-6d94-439a-9009-51556d8fcfd4)
start
![Captura de tela 2024-08-03 163134](https://github.com/user-attachments/assets/79cb41b7-c9ae-4f9a-bec6-7586cb0bcf13)
test units
![Captura de tela 2024-08-03 162818](https://github.com/user-attachments/assets/3cbbb85b-4e19-4f67-a661-f27756a271ab)

2024-08-04 01:40 UTC, sartori00 approved these changes

2024-08-04 22:51 UTC, 8bitbeard approved these changes

2024-08-04 22:55 UTC, alemiranda-dev approved these changes

2024-08-05 02:21 UTC, DiguyaDeveloper requested changes

2024-08-05 03:39 UTC, JessicaRodriguesdc commented on src/main/java/br/com/fiap/tech_challenge/core/domain/models/enums/StatusOrderEnum.java
> +public enum StatusOrderEnum {
@DiguyaDeveloper feito

2024-08-05 22:05 UTC, DiguyaDeveloper approved these changes

2024-08-05 23:32 UTC, merged