chore: 🗃️ Creating inserts values migration
JessicaRodriguesdc/fiap-soat-tech-challenge pull request #25
Opened 2024-08-04 01:13 UTC by JessicaRodriguesdc

Inserts Values Migration
- A migration was created regarding values inserts.
- Evidence of the feature:
build
![Captura de tela 2024-08-03 220604](https://github.com/user-attachments/assets/abd03286-e3c2-477b-b8ed-26dc8e775e28)
start
![Captura de tela 2024-08-03 220204](https://github.com/user-attachments/assets/8d2c50a3-175b-4ebd-b10c-af959ce2c08a)
script execution
![Captura de tela 2024-08-03 215822](https://github.com/user-attachments/assets/bc594885-34c7-41f3-b3ab-cb28035457f9)
![Captura de tela 2024-08-03 215944](https://github.com/user-attachments/assets/c2ba35f5-ac90-423e-816e-6967ad163147)
![Captura de tela 2024-08-03 220008](https://github.com/user-attachments/assets/37cf9ea5-34b4-4bb3-8c46-83bf38d3f4e2)
![Captura de tela 2024-08-03 220040](https://github.com/user-attachments/assets/7e445c75-6eea-4301-90b8-2847b88ba085)
![Captura de tela 2024-08-03 220113](https://github.com/user-attachments/assets/7e986926-0927-4954-b45d-65437d28c048)
![Captura de tela 2024-08-03 220133](https://github.com/user-attachments/assets/6a250cbe-1c17-4da2-92b5-fd3bd416502d)

2024-08-04 01:44 UTC, sartori00 requested changes

2024-08-04 01:44 UTC, sartori00 commented on src/main/resources/db/migration/V5__inserts_values.sql
> +INSERT INTO CUSTOMER_ORDER (ID, CUSTOMER_ID, AMOUNT, PAYMENT_ID, SEQUENCE, STATUS, IS_PAID, CREATED_AT, UPDATED_AT) VALUES
Jessica, uma das alterações que fiz hoje diz respeito ao campo Sequence desta tabela, agora esta coluna esta utilizando a função de Sequence do Postgres, pra funcionar este insert preciso que você omita o campo SEQUENCE e os valores que estão sendo setados pra ele nos Values.

2024-08-04 02:02 UTC, sartori00 commented on src/main/resources/db/migration/V5__inserts_values.sql
> +INSERT INTO CUSTOMER_ORDER (ID, CUSTOMER_ID, AMOUNT, PAYMENT_ID, SEQUENCE, STATUS, IS_PAID, CREATED_AT, UPDATED_AT) VALUES
Testei aqui na minha branch o V5 sem a coluna SEQUENCE no insert de CUSTOMER_ORDER e deu certinho. O banco pegou a sequence automaticamente. 

![Captura de tela 2024-08-03 230252](https://github.com/user-attachments/assets/c4fa0fa7-036e-47b3-9230-e3325b203558)

2024-08-04 02:21 UTC, JessicaRodriguesdc commented on src/main/resources/db/migration/V5__inserts_values.sql
> +INSERT INTO CUSTOMER_ORDER (ID, CUSTOMER_ID, AMOUNT, PAYMENT_ID, SEQUENCE, STATUS, IS_PAID, CREATED_AT, UPDATED_AT) VALUES
@sartori00 Perfeito, vou alterar aqui

2024-08-04 02:24 UTC, sartori00 approved these changes
tooppp

2024-08-04 22:00 UTC, alemiranda-dev approved these changes

2024-08-04 22:50 UTC, 8bitbeard approved these changes

2024-08-05 23:33 UTC, DiguyaDeveloper approved these changes

2024-08-05 23:34 UTC, merged