docs: 📖 Including readme
JessicaRodriguesdc/fiap-soat-tech-challenge pull request #26
Opened 2024-08-04 22:48 UTC by alemiranda-dev

- Only including readme on project

2024-08-04 23:00 UTC, 8bitbeard approved these changes

2024-08-05 00:56 UTC, JessicaRodriguesdc approved these changes

2024-08-05 03:52 UTC, JessicaRodriguesdc requested changes

2024-08-05 03:52 UTC, JessicaRodriguesdc commented on README.md
> +### Pré-requisitos
@alemiranda-dev Não seria interessante add também o docker ? e os passoas para execultalo via ele

2024-08-05 22:55 UTC, DiguyaDeveloper approved these changes

2024-08-06 00:02 UTC, sartori00 approved these changes

2024-08-08 22:25 UTC, 8bitbeard commented on README.md
> +### Pré-requisitos
Adicionei na documentação os dados referentes ao dockerfile, docker registry (docker hub) e docker-compose!

2024-08-08 23:22 UTC, JessicaRodriguesdc approved these changes

2024-08-08 23:24 UTC, merged