docs: 📖 add link of swagger and miro
JessicaRodriguesdc/fiap-soat-tech-challenge pull request #37
Opened 2024-08-09 21:49 UTC by alemiranda-dev

Include MIRO with event storming and Swagger link. License removed.

2024-08-09 23:00 UTC, JessicaRodriguesdc approved these changes

2024-08-09 23:09 UTC, sartori00 requested changes
O link pro swagger ta errado, o certo é http://localhost:8357/api/swagger-ui/index.html

2024-08-10 00:00 UTC, DiguyaDeveloper approved these changes

2024-08-10 00:06 UTC, sartori00 approved these changes

2024-08-10 00:06 UTC, merged