:sparkles: feat: Creating the Fake Checkout port and adapter
JessicaRodriguesdc/fiap-soat-tech-challenge pull request #6
Opened 2024-07-22 02:06 UTC by 8bitbeard

Creating the Fake Checkout port and adapter

- This PR contains an approach idea for the fake checkout. It has the PaymentGateway port and PaymentGateway Adapter, mocking the generateQRCode method and mocking the CheckPaymentStatus method.
- This PR doesn't takes on account the chosen payment gateway yet, since this project phase doesn't include the actual payment gateway implementation.
- The two methods implemented on the port are not real, and WILL be changed on the future, when the actual payment gateway (Mercado Pago) is implemented

2024-07-29 00:24 UTC, JessicaRodriguesdc requested changes

2024-07-29 00:24 UTC, JessicaRodriguesdc commented on src/main/java/br/com/fiap/tech_challenge/adapters/driver/api/controller/FakeCheckoutController.java
> +    private ResponseEntity<OrderResponseDTO> create(
@8bitbeard Aqui não fica melhor checkout ao invez de "create" visto que estaremos de fato fazendo o checkout e não criando nada ?

2024-07-29 00:24 UTC, JessicaRodriguesdc commented on src/main/resources/db/migration/V5__update-order-table_add_payment_id.sql
> +ADD COLUMN PAYMENT_ID VARCHAR(255);
@8bitbeard Faz sentido criar um arquivo para editar ? visto que ainda não temos um banco "fisico", talvez daria para editar a propeia migração como você fez mudando o nome.

2024-07-29 00:41 UTC, 8bitbeard commented on src/main/java/br/com/fiap/tech_challenge/adapters/driver/api/controller/FakeCheckoutController.java
> +    private ResponseEntity<OrderResponseDTO> create(
Boa, faz sentido sim! Vou ajustar o nome do método

2024-07-29 00:42 UTC, 8bitbeard commented on src/main/resources/db/migration/V5__update-order-table_add_payment_id.sql
> +ADD COLUMN PAYMENT_ID VARCHAR(255);
Concordo! Porém essa alteração faz parte do PR do Diego, eu repliquei aqui nesse PR só pra ter as tabelas e fazer os testes do checkout. Dai acredito que vale solicitar o ajuste no PR de origem

2024-07-29 18:16 UTC, JessicaRodriguesdc commented on src/main/resources/db/migration/V5__update-order-table_add_payment_id.sql
> +ADD COLUMN PAYMENT_ID VARCHAR(255);
@8bitbeard Aqui falta so ajustar que o Diego ja ajustou la

2024-07-29 18:17 UTC, JessicaRodriguesdc commented on src/main/java/br/com/fiap/tech_challenge/adapters/driver/api/controller/FakeCheckoutController.java
> +    @PostMapping()
@8bitbeard aqui não precisa dos parenteses

2024-07-29 22:15 UTC, sartori00 commented on src/main/java/br/com/fiap/tech_challenge/adapters/driven/infra/repository/OrderRepository.java
> +    @Query("SELECT MAX(o.sequence) FROM OrderEntity o WHERE o.createdAt >= :startOfDay AND o.createdAt < :endOfDay")
Man, pra uma proxima PR, da uma olhada nisso aqui, dei uma breve pesquisada e descobri que o Postgres suporta criação de Sequences pode ser que isso resolva o problema da sequence do pedido.
https://www.postgresql.org/docs/current/sql-createsequence.html

2024-07-29 22:22 UTC, sartori00 approved these changes

2024-07-29 22:22 UTC, sartori00 commented on src/main/java/br/com/fiap/tech_challenge/adapters/driver/api/dto/OrderResponseDTO.java
Você não ia seguir com os contratos em camel?

2024-07-29 23:21 UTC, alemiranda-dev approved these changes

2024-07-30 01:45 UTC, 8bitbeard commented on src/main/resources/db/migration/V5__update-order-table_add_payment_id.sql
> +ADD COLUMN PAYMENT_ID VARCHAR(255);
Pronto, como o merge do PR do Diego foi feito, atualizei minha branch e o arquivo já está atualizado!

2024-07-30 01:45 UTC, 8bitbeard commented on src/main/java/br/com/fiap/tech_challenge/adapters/driver/api/controller/FakeCheckoutController.java
> +    @PostMapping()
Removidos!

2024-07-30 01:46 UTC, 8bitbeard commented on src/main/java/br/com/fiap/tech_challenge/adapters/driven/infra/repository/OrderRepository.java
> +    @Query("SELECT MAX(o.sequence) FROM OrderEntity o WHERE o.createdAt >= :startOfDay AND o.createdAt < :endOfDay")
Com o merge da main na minha branch, essa alteração deixou de fazer parte desse PR! (Já que era apenas um clone da branch do Diego, pra trazer os arquivos necessários pro teste do fake checkout pra cá)

2024-07-30 01:46 UTC, 8bitbeard commented on src/main/java/br/com/fiap/tech_challenge/adapters/driver/api/dto/OrderResponseDTO.java
Não só ia como fui! Os ajustes foram feitos hehe

2024-07-30 02:30 UTC, sartori00 commented on src/main/java/br/com/fiap/tech_challenge/adapters/driver/api/dto/OrderResponseDTO.java
é um monstro saindo da jaula!

2024-07-30 02:31 UTC, JessicaRodriguesdc approved these changes

2024-07-30 21:02 UTC, alemiranda-dev approved these changes

2024-07-30 23:38 UTC, alemiranda-dev approved these changes

2024-07-30 23:39 UTC, JessicaRodriguesdc approved these changes

2024-07-30 23:39 UTC, sartori00 approved these changes

2024-07-30 23:43 UTC, DiguyaDeveloper approved these changes

2024-07-30 23:46 UTC, merged