feature: ✨ Creating Endpoint to create product
JessicaRodriguesdc/fiap-soat-tech-challenge pull request #8
Opened 2024-07-24 00:24 UTC by JessicaRodriguesdc

## Product Creation Endpoint

- Was added class structure referring to the Product table in the project architecture
- Was added the product creation endpoint
- Evidence of the feature:
request
![Captura de tela 2024-07-23 205317](https://github.com/user-attachments/assets/c88fa912-dd8e-4050-a1d0-62e0af8150a2)
![Captura de tela 2024-07-23 205340](https://github.com/user-attachments/assets/d06f59c5-76b9-40f1-84fa-b1fd8186d24f)
![Captura de tela 2024-07-23 205412](https://github.com/user-attachments/assets/e5767786-7237-41fa-ae0f-bd548fe7f36f)
![Captura de tela 2024-07-23 205434](https://github.com/user-attachments/assets/f11662e5-c171-4451-b0c3-be27a621af67)
![Captura de tela 2024-07-23 205450](https://github.com/user-attachments/assets/c5b4d6c9-ba7c-47b9-baea-77a2e16f0e4f)
respont
![Captura de tela 2024-07-23 205734](https://github.com/user-attachments/assets/63770dbb-774f-42a0-bdde-d27f27746f94)
registration in the database
![Captura de tela 2024-07-23 205910](https://github.com/user-attachments/assets/069af103-cf5e-4526-9523-5c6d7c6f1013)
start
![Captura de tela 2024-07-23 211130](https://github.com/user-attachments/assets/70a18b15-2604-4383-8759-78e3f3103ba0)

2024-07-24 23:35 UTC, DiguyaDeveloper requested changes

2024-07-24 23:35 UTC, DiguyaDeveloper commented on src/main/java/br/com/fiap/tech_challenge/core/domain/models/Product.java
> +    private Double price;
Consegue alterar para BigDecimal?

2024-07-24 23:39 UTC, alemiranda-dev approved these changes
Looks good to me!!

2024-07-25 00:50 UTC, DiguyaDeveloper approved these changes

2024-07-25 00:53 UTC, sartori00 approved these changes
The  father is approve

2024-07-25 00:53 UTC, merged